[Definition]

# ban IP
actionban = /home/cyber1/ips-ai/venv/bin/python3 /home/cyber1/ips-ai/ban/extractor.py <ip>

# unban IP
actionunban = /home/cyber1/ips-ai/venv/bin/python3 /home/cyber1/ips-ai/ban/unban_trigger.py <ip>

# optional
actionstart =
actionstop =
actioncheck =
